app = "qiskitqb-ici5dq"   # <-- paste the exact slug here
primary_region = "fra"

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1      # <- set to 0 for $0 idle cost
  force_https = true

  [http_service.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

[[vm]]
  size = "shared-cpu-1x"
  memory = "1024mb"
