app = "qiskitqb"   # CHANGE if taken
primary_region = "fra"         # close to Basel

[http_service]
  internal_port = 8080
  auto_stop_machines = true    # scale to 0 when idle
  auto_start_machines = true   # wake on first request
  min_machines_running = 0     # keep $0 idle cost
  force_https = true

  [http_service.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

[[vm]]
  size = "shared-cpu-1x"
  memory = "1024mb"
