name: Fly Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/fly.yml'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Sanity check
      - name: Show server dir
        working-directory: server
        run: |
          pwd
          ls -la
          echo "---- fly.toml ----"; sed -n '1,60p' fly.toml || true
          echo "---- Dockerfile ----"; sed -n '1,60p' Dockerfile || true

   - name: Deploy (server/)
  working-directory: server
  run: flyctl deploy --remote-only --app qiskitqb-ici5dq
  env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

